###
GET http://localhost:3000/api/product/list
Content-type: 'application/json'

###
GET http://localhost:3000/api/category
Content-type: 'application/json'

###
GET http://localhost:3000/api/cms/category
Content-type: 'application/json'